export type VendorSettings = {
  vendorSettingsId: string;
  vendorId: string;
  isAllowedGiftCards: boolean;
  isAllowedDonations: boolean;
  emailBackgroundSettings: string;
  referenceQuoteAIPrompt: string;
  referenceCaseStudyAIPrompt: string;
  quoteStepEnabled: boolean;
  reviewStepEnabled: boolean;
  questionsAndAnswersStepEnabled: boolean;
  caseStudyStepEnabled: boolean;
  testimonialStepEnabled: boolean;
  g2ReviewEnabled: boolean;
  personalizedVideoStoryboardId: string | null;
  addonsStepEnabled: boolean;
  publicSpeakingEnabled: boolean;
  webinarsEnabled: boolean;
  productFeedbackEnabled: boolean;
  socialPresenceEnabled: boolean;
  roundTableEnabled: boolean;
  podcastEnabled: boolean;
  firstToKnowEnabled: boolean;
  interviewsEnabled: boolean;
  collaborationNewProductEnabled: boolean;
  advisoryBoardEnabled: boolean;
  contentApprovalRequired: boolean;
  deetoReviewRequired: boolean;
  allowAnonymousReference: boolean;
  referenceRegistrationUrl: string | null;
  languagePacks: string;
  giftcardOptions: string | null;
  g2ReviewUrl: string;
  meetingLengthInMinutes: number;
  currencyPrefix: string;
  currencyPostfix: string;
  referralUrl: string | null;
};

export type Vendor = {
  vendorId: string;
  name: string;
  accountLevel: string;
  sendEmailOnBehalf: string | null;
  activationDate: string;
  defaultCreditAmountPerMeeting: number;
  avatarId: string;
  appLogoId: string;
  createdAt: string;
  updatedAt: string;
  settings: VendorSettings;
};
