name: Deeto html builder dev build

on:
  push:
    branches:
      - production

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Set the right config file
        run: |
          cp src/config/config.prod.js src/config/config.js

      - name: Install dependencies
        run: bun install

      - name: Build static file
        run: bun run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build s3://deeto-widget-production/v2

      - name: Sync widget metadata to S3 bucket
        run: aws s3 cp public/widget/metadata.json s3://deeto-images/widgetData/metadata.json

      - name: Sync self registration to S3 bucket
        run: aws s3 cp public/self-registration/ s3://deeto-images/self-registration-content/ --recursive

      - name: Sync referral program to S3 bucket
        run: |
          aws s3 cp public/affiliate_v1.html s3://deeto-images/referralProgramTemplates/affiliate_v1.html 
          aws s3 cp public/referral_v1.html s3://deeto-images/referralProgramTemplates/referral_v1.html
